name: Deployment

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.127.0'

      - name: Build Site
        run: hugo --minify

      - name: Deploy Pages
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEPLOY_SITE_PERSONAL_ACCESS_TOKEN }}

        with:
          source-directory: public/
          destination-github-username: muffinman989
          destination-repository-name: cvsite
          user-email: merlin989@gmail.com

      # test get variable exported by push-to-another-repository
      - name: Test
        run: echo $DESTINATION_CLONED_DIRECTORY